const brainrots = [
  // Common
  {name:"Capibarelino Apelino",color:"#fff"},
  {name:"Daga-Tubo",color:"#fff"},
  {name:"FluriFlura",color:"#fff"},
  {name:"Holy Arepa",color:"#fff"},
  {name:"La Foca Lasagnetta",color:"#fff"},
  {name:"Lirili Larila",color:"#fff"},
  {name:"Noobini Lapis Lazulini",color:"#fff"},
  {name:"Noobini Pizzanini",color:"#fff"},
  {name:"Noobini Santanini",color:"#fff"},
  {name:"Penguino Pizza",color:"#fff"},
  {name:"Pipi Corni",color:"#fff"},
  {name:"Pipi Kiwi",color:"#fff"},
  {name:"Pipi Peachi",color:"#fff"},
  {name:"Pipi Strawberry",color:"#fff"},
  {name:"Raccooni Jandelini",color:"#fff"},
  {name:"Slimo Li Appluni",color:"#fff"},
  {name:"Svinina Bombardino",color:"#fff"},
  {name:"Talpa Di Fero",color:"#fff"},
  {name:"Tartaragno",color:"#fff"},
  {name:"Tim Cheese",color:"#fff"},
  // Rare
  {name:"A A A Sahur",color:"green"},
  {name:"B B B Sahur",color:"green"},
  {name:"Bandito Bobritto",color:"green"},
  {name:"Boneca Ambalabu",color:"green"},
  {name:"Brindolero Brindolina",color:"green"},
  {name:"C C C Sahur",color:"green"},
  {name:"Cacto Hipopotamo",color:"green"},
  {name:"Cupcake Koala",color:"green"},
  {name:"D D D Sahur",color:"green"},
  {name:"Dragonfruti Axuluti",color:"green"},
  {name:"Frogo Elfo",color:"green"},
  {name:"Gangster Footera",color:"green"},
  {name:"Gingobalo Gingobali",color:"green"},
  {name:"Granate Frogiate",color:"green"},
  {name:"Kiwitto Bandito",color:"green"},
  {name:"Kurmaludin",color:"green"},
  {name:"Libur Telah Tiba",color:"green"},
  {name:"Papete Pakipato",color:"green"},
  {name:"Pengolino Nuvoletto",color:"green"},
  {name:"Pinealotto Fruttarino",color:"green"},
  {name:"Pipi Avocado",color:"green"},
  {name:"Raspberrini Rabbitini",color:"green"},
  {name:"Ta Ta Ta Ta Sahur",color:"green"},
  {name:"Tanggu Tanggu Sahur",color:"green"},
  {name:"Tremonchino Trembolão",color:"green"},
  {name:"Tric Trac Baraboom",color:"green"},
  {name:"Trippi Troppi",color:"green"},
  // Epic
  {name:"Avocadini Antilopini",color:"purple"},
  {name:"Avocadini Guffo",color:"purple"},
  {name:"Bambini Crostini",color:"purple"},
  {name:"Bananita Dolphinita",color:"purple"},
  {name:"Bandito Axolito",color:"purple"},
  {name:"Brr Brr Patapim",color:"purple"},
  {name:"Brri Brri Bicus Dicus Bombicus",color:"purple"},
  {name:"Cappuccino Assassino",color:"purple"},
  {name:"Doi Doi Do",color:"purple"},
  {name:"Don Don Don Don Don Satur",color:"purple"},
  {name:"E E E Sahur",color:"purple"},
  {name:"F F F Sahur",color:"purple"},
  {name:"Frogato Pirato",color:"purple"},
  {name:"G G G Sahur",color:"purple"},
  {name:"Gato Celesto",color:"purple"},
  {name:"Gatito Melonito",color:"purple"},
  {name:"Granate Owlate",color:"purple"},
  {name:"H H H Sahur",color:"purple"},
  {name:"I I I Sahur",color:"purple"},
  {name:"J J J Sahur",color:"purple"},
  {name:"K K K Sahur",color:"purple"},
  {name:"Kudanile Astronaute",color:"purple"},
  {name:"L L L Sahur",color:"purple"},
  {name:"M M M Sahur",color:"purple"},
  {name:"Malame Amarele",color:"purple"},
  {name:"Mangolini Parrocini",color:"purple"},
  {name:"Mummio Rappitto",color:"purple"},
  {name:"N N N Sahur",color:"purple"},
  {name:"Ñ Ñ Ñ Sahur",color:"purple"},
  {name:"O O O Sahur",color:"purple"},
  {name:"P P P Sahur",color:"purple"},
  {name:"Patita Cerealita",color:"purple"},
  {name:"Pelicini Panini",color:"purple"},
  {name:"Penguin Tree",color:"purple"},
  {name:"Penguino Cocosino",color:"purple"},
  {name:"Perochello Lemonchello",color:"purple"},
  {name:"Pipi Lime",color:"purple"},
  {name:"Pippi Poppa",color:"purple"},
  {name:"Q Q Q Sahur",color:"purple"},
  {name:"Quivi Tortigi",color:"purple"},
  {name:"R R R Sahur",color:"purple"},
  {name:"Salamino Penguino",color:"purple"},
  {name:"Ti Ti Ti Sahur",color:"purple"},
  {name:"Tri Tri Tri Tri Sahur",color:"purple"},
  {name:"Triki Traka Telas",color:"purple"},
  {name:"Trulimero Trulicina",color:"purple"},
  {name:"Wombo Rollo",color:"purple"},
  // Weitere Kategorien (Legendary, Mythic, Brainrot God, Secret, OG) können hier genauso ergänzt werden
];
