const RARITY_META = {
  "Common":      { icon:"⚪", color:"#9ca3af", glow:"rgba(156,163,175,0.5)" },
  "Rare":        { icon:"🟢", color:"#4ade80", glow:"rgba(74,222,128,0.5)" },
  "Epic":        { icon:"🟣", color:"#c084fc", glow:"rgba(192,132,252,0.5)" },
  "Legendary":   { icon:"🟡", color:"#fbbf24", glow:"rgba(251,191,36,0.5)" },
  "Mythic":      { icon:"🔴", color:"#f87171", glow:"rgba(248,113,113,0.5)" },
  "God":         { icon:"🧠", color:"#22d3ee", glow:"rgba(34,211,238,0.5)" },
  "Secret":      { icon:"⚫", color:"#a78bfa", glow:"rgba(167,139,250,0.5)" },
  "OG":          { icon:"👑", color:"#f59e0b", glow:"rgba(245,158,11,0.7)" },
};

const brainrots = [
// ⚪ Common
{name:"Capibarelino Apelino",rarity:"Common"},
{name:"Daga-Tubo",rarity:"Common"},
{name:"FluriFlura",rarity:"Common"},
{name:"Holy Arepa",rarity:"Common"},
{name:"La Foca Lasagnetta",rarity:"Common"},
{name:"Lirili Larila",rarity:"Common"},
{name:"Noobini Lapis Lazulini",rarity:"Common"},
{name:"Noobini Pizzanini",rarity:"Common"},
{name:"Noobini Santanini",rarity:"Common"},
{name:"Penguino Pizza",rarity:"Common"},
{name:"Pipi Corni",rarity:"Common"},
{name:"Pipi Kiwi",rarity:"Common"},
{name:"Pipi Peachi",rarity:"Common"},
{name:"Pipi Strawberry",rarity:"Common"},
{name:"Raccooni Jandelini",rarity:"Common"},
{name:"Slimo Li Appluni",rarity:"Common"},
{name:"Svinina Bombardino",rarity:"Common"},
{name:"Talpa Di Fero",rarity:"Common"},
{name:"Tartaragno",rarity:"Common"},
{name:"Tim Cheese",rarity:"Common"},
// 🟢 Rare
{name:"A A A Sahur",rarity:"Rare"},
{name:"B B B Sahur",rarity:"Rare"},
{name:"Bandito Bobritto",rarity:"Rare"},
{name:"Boneca Ambalabu",rarity:"Rare"},
{name:"Brindolero Brindolina",rarity:"Rare"},
{name:"C C C Sahur",rarity:"Rare"},
{name:"Cacto Hipopotamo",rarity:"Rare"},
{name:"Cupcake Koala",rarity:"Rare"},
{name:"D D D Sahur",rarity:"Rare"},
{name:"Dragonfruti Axuluti",rarity:"Rare"},
{name:"Frogo Elfo",rarity:"Rare"},
{name:"Gangster Footera",rarity:"Rare"},
{name:"Gingobalo Gingobali",rarity:"Rare"},
{name:"Granate Frogiate",rarity:"Rare"},
{name:"Kiwitto Bandito",rarity:"Rare"},
{name:"Kurmaludin",rarity:"Rare"},
{name:"Libur Telah Tiba",rarity:"Rare"},
{name:"Papete Pakipato",rarity:"Rare"},
{name:"Pengolino Nuvoletto",rarity:"Rare"},
{name:"Pinealotto Fruttarino",rarity:"Rare"},
{name:"Pipi Avocado",rarity:"Rare"},
{name:"Raspberrini Rabbitini",rarity:"Rare"},
{name:"Ta Ta Ta Ta Sahur",rarity:"Rare"},
{name:"Tanggu Tanggu Sahur",rarity:"Rare"},
{name:"Tremonchino Trembolão",rarity:"Rare"},
{name:"Tric Trac Baraboom",rarity:"Rare"},
{name:"Trippi Troppi",rarity:"Rare"},
// 🟣 Epic
{name:"Avocadini Antilopini",rarity:"Epic"},
{name:"Avocadini Guffo",rarity:"Epic"},
{name:"Bambini Crostini",rarity:"Epic"},
{name:"Bananita Dolphinita",rarity:"Epic"},
{name:"Bandito Axolito",rarity:"Epic"},
{name:"Brr Brr Patapim",rarity:"Epic"},
{name:"Brri Brri Bicus Dicus Bombicus",rarity:"Epic"},
{name:"Cappuccino Assassino",rarity:"Epic"},
{name:"Doi Doi Do",rarity:"Epic"},
{name:"Don Don Don Don Don Satur",rarity:"Epic"},
{name:"E E E Sahur",rarity:"Epic"},
{name:"F F F Sahur",rarity:"Epic"},
{name:"Frogato Pirato",rarity:"Epic"},
{name:"G G G Sahur",rarity:"Epic"},
{name:"Gato Celesto",rarity:"Epic"},
{name:"Gatito Melonito",rarity:"Epic"},
{name:"Granate Owlate",rarity:"Epic"},
{name:"H H H Sahur",rarity:"Epic"},
{name:"I I I Sahur",rarity:"Epic"},
{name:"J J J Sahur",rarity:"Epic"},
{name:"K K K Sahur",rarity:"Epic"},
{name:"Kudanile Astronaute",rarity:"Epic"},
{name:"L L L Sahur",rarity:"Epic"},
{name:"M M M Sahur",rarity:"Epic"},
{name:"Malame Amarele",rarity:"Epic"},
{name:"Mangolini Parrocini",rarity:"Epic"},
{name:"Mummio Rappitto",rarity:"Epic"},
{name:"N N N Sahur",rarity:"Epic"},
{name:"Ñ Ñ Ñ Sahur",rarity:"Epic"},
{name:"O O O Sahur",rarity:"Epic"},
{name:"P P P Sahur",rarity:"Epic"},
{name:"Patita Cerealita",rarity:"Epic"},
{name:"Pelicini Panini",rarity:"Epic"},
{name:"Penguin Tree",rarity:"Epic"},
{name:"Penguino Cocosino",rarity:"Epic"},
{name:"Perochello Lemonchello",rarity:"Epic"},
{name:"Pipi Lime",rarity:"Epic"},
{name:"Pippi Poppa",rarity:"Epic"},
{name:"Q Q Q Sahur",rarity:"Epic"},
{name:"Quivi Tortigi",rarity:"Epic"},
{name:"R R R Sahur",rarity:"Epic"},
{name:"Salamino Penguino",rarity:"Epic"},
{name:"Ti Ti Ti Sahur",rarity:"Epic"},
{name:"Tri Tri Tri Tri Sahur",rarity:"Epic"},
{name:"Triki Traka Telas",rarity:"Epic"},
{name:"Trulimero Trulicina",rarity:"Epic"},
{name:"Wombo Rollo",rarity:"Epic"},
// 🟡 Legendary
{name:"Aaaaaaaro Hamstero",rarity:"Legendary"},
{name:"Aduh 9 April",rarity:"Legendary"},
{name:"Ananasita Owlita",rarity:"Legendary"},
{name:"Ballerina Cappuccina",rarity:"Legendary"},
{name:"Blueberrini Octopusini",rarity:"Legendary"},
{name:"Boom Boom Boom Sahur",rarity:"Legendary"},
{name:"Brr Brr Gangster Gusini",rarity:"Legendary"},
{name:"Buho de Cielo",rarity:"Legendary"},
{name:"Buho de Fuego",rarity:"Legendary"},
{name:"Burbaloni Loliloli",rarity:"Legendary"},
{name:"Capibomba Atomica",rarity:"Legendary"},
{name:"Caramello Filtrello",rarity:"Legendary"},
{name:"Chef Crabracadabra",rarity:"Legendary"},
{name:"Chimpazini Bananini",rarity:"Legendary"},
{name:"Chocco Bunny",rarity:"Legendary"},
{name:"Clickerino Crabo",rarity:"Legendary"},
{name:"Coccodrillo Formaggioso",rarity:"Legendary"},
{name:"Cocosini Mama",rarity:"Legendary"},
{name:"Dardirdurderdor",rarity:"Legendary"},
{name:"Dolcettina Doggettina",rarity:"Legendary"},
{name:"Dolcettoni Doggettoni",rarity:"Legendary"},
{name:"Garale Tarale",rarity:"Legendary"},
{name:"Giraffa Banani",rarity:"Legendary"},
{name:"Glorbo Fruttodrillo",rarity:"Legendary"},
{name:"Heartini Cupidini",rarity:"Legendary"},
{name:"Lionel Cactuseli",rarity:"Legendary"},
{name:"Pandaccini Bananini",rarity:"Legendary"},
{name:"Pi Pi Watermelon",rarity:"Legendary"},
{name:"Pipi Potato",rarity:"Legendary"},
{name:"Pipi Tomato",rarity:"Legendary"},
{name:"Puffaball",rarity:"Legendary"},
{name:"Quackula",rarity:"Legendary"},
{name:"Quivioli Ameleonni",rarity:"Legendary"},
{name:"S S S Sahur",rarity:"Legendary"},
{name:"Saphiri Crocodrili",rarity:"Legendary"},
{name:"Sealo Regalo",rarity:"Legendary"},
{name:"Seraphino Gruyero",rarity:"Legendary"},
{name:"Sigma Boy",rarity:"Legendary"},
{name:"Sigma Girl",rarity:"Legendary"},
{name:"Signore Carapace",rarity:"Legendary"},
{name:"Strang Strang Strang Sahur",rarity:"Legendary"},
{name:"Strawberelli Flamingelli",rarity:"Legendary"},
{name:"Suricatelli Bananelli",rarity:"Legendary"},
{name:"T T T Sahur",rarity:"Legendary"},
{name:"Tirilikalika Tirilikalako",rarity:"Legendary"},
{name:"Trulibau Trulibanana",rarity:"Legendary"},
{name:"Tu Tu Tu Tu Tu Sahur",rarity:"Legendary"},
{name:"U U U Sahur",rarity:"Legendary"},
{name:"V V V Sahur",rarity:"Legendary"},
{name:"W W W Sahur",rarity:"Legendary"},
{name:"X X X Sahur",rarity:"Legendary"},
// 🔴 Mythic
{name:"Avocadorilla",rarity:"Mythic"},
{name:"Bananito Bandito",rarity:"Mythic"},
{name:"Bantalero Bobo'o",rarity:"Mythic"},
{name:"Berenjello Angello",rarity:"Mythic"},
{name:"Bombardiro Crocodilo",rarity:"Mythic"},
{name:"Bombombini Gusini",rarity:"Mythic"},
{name:"Brutto Gialutto",rarity:"Mythic"},
{name:"Cachorrito Melonito",rarity:"Mythic"},
{name:"Capybarelli Camionelli",rarity:"Mythic"},
{name:"Carloo",rarity:"Mythic"},
{name:"Carrotini Brainini",rarity:"Mythic"},
{name:"Cavallo Virtuoso",rarity:"Mythic"},
{name:"Centrucci Nuclucci",rarity:"Mythic"},
{name:"Dinosahurus",rarity:"Mythic"},
{name:"Eaglucci Watermelucci",rarity:"Mythic"},
{name:"Elephanto Frigo",rarity:"Mythic"},
{name:"Ferro Ferro Ferro Sahur",rarity:"Mythic"},
{name:"Fizzy Soda",rarity:"Mythic"},
{name:"Ganganzelli Trulala",rarity:"Mythic"},
{name:"Gorillo Subwoofero",rarity:"Mythic"},
{name:"Gorillo Watermelondrillo",rarity:"Mythic"},
{name:"Harpuccino",rarity:"Mythic"},
{name:"Jacko Spaventosa",rarity:"Mythic"},
{name:"Jingle Jingle Sahur",rarity:"Mythic"},
{name:"Las Avocadinis",rarity:"Mythic"},
{name:"Lerulerulerule",rarity:"Mythic"},
{name:"Los Noobinis",rarity:"Mythic"},
{name:"Magi Ribbitini",rarity:"Mythic"},
{name:"Margheriti Octopusini",rarity:"Mythic"},
{name:"Orangutini Ananassini",rarity:"Mythic"},
{name:"Peachi Owlici",rarity:"Mythic"},
{name:"Pingvinator Termoregullator",rarity:"Mythic"},
{name:"Pipi Coffee",rarity:"Mythic"},
{name:"Pipi Mango",rarity:"Mythic"},
{name:"Pussini Sushini",rarity:"Mythic"},
{name:"Rhino Helicopterino",rarity:"Mythic"},
{name:"Sahurpalma Naufragio",rarity:"Mythic"},
{name:"Spioniro Golubiro",rarity:"Mythic"},
{name:"Spongini Quackini",rarity:"Mythic"},
{name:"Te Te Te Sahur",rarity:"Mythic"},
{name:"Tigrili Oranguli",rarity:"Mythic"},
{name:"Tigrilini Watermelini",rarity:"Mythic"},
{name:"Tob Tobi Tobi",rarity:"Mythic"},
{name:"Toiletto Focaccino",rarity:"Mythic"},
{name:"Tracoducotulu Delapeladustuz",rarity:"Mythic"},
{name:"Tralachicko Jockerito",rarity:"Mythic"},
{name:"Tree Tree Tree Sahur",rarity:"Mythic"},
{name:"Trilalero Tralalima",rarity:"Mythic"},
{name:"Y Y Y Sahur",rarity:"Mythic"},
{name:"Z Z Z Sahur",rarity:"Mythic"},
{name:"Zarzerzar Zurzur",rarity:"Mythic"},
{name:"Zibra Zubra Zibralini",rarity:"Mythic"},
{name:"Mythic Lucky Block",rarity:"Mythic"},
// 🧠 Brainrot God
{name:"Ä Ü Ö Ä Ü Ö Ä Sahur",rarity:"God"},
{name:"Alessio",rarity:"God"},
{name:"Antonio",rarity:"God"},
{name:"Aquanaut",rarity:"God"},
{name:"Astrolero Cervalero",rarity:"God"},
{name:"Ballerina Peppermintina",rarity:"God"},
{name:"Ballerino Lololo",rarity:"God"},
{name:"Ballerino Wolfolino",rarity:"God"},
{name:"Belula Beluga",rarity:"God"},
{name:"Boba Panda",rarity:"God"},
{name:"Bombardini Tortinii",rarity:"God"},
{name:"Brasilini Berimbini",rarity:"God"},
{name:"Brr Brr Mamabim",rarity:"God"},
{name:"Brr es Teh Patipum",rarity:"God"},
{name:"Buho De Noelo",rarity:"God"},
{name:"Bulbito Bandito Traktorito",rarity:"God"},
{name:"Capi Taco",rarity:"God"},
{name:"Cappuccino Clownino",rarity:"God"},
{name:"Chihuanini Taconini",rarity:"God"},
{name:"Chrismasmamat",rarity:"God"},
{name:"Coco Elefanto",rarity:"God"},
{name:"Cocofanto Elefanto",rarity:"God"},
{name:"Corn Corn Corn Sahur",rarity:"God"},
{name:"Divino Platypio",rarity:"God"},
{name:"Dolphini Jetskini",rarity:"God"},
{name:"Dug Dug Dug",rarity:"God"},
{name:"Dumborino Miracello",rarity:"God"},
{name:"Espresso Signora",rarity:"God"},
{name:"Extinct Ballerina",rarity:"God"},
{name:"Frio Ninja",rarity:"God"},
{name:"Gattatino Nyanino",rarity:"God"},
{name:"Gattito Tacoto",rarity:"God"},
{name:"Girafa Celestre",rarity:"God"},
{name:"Jacko Jack Jack",rarity:"God"},
{name:"Karkerheart Luvkur",rarity:"God"},
{name:"Las Capuchinas",rarity:"God"},
{name:"Los Bombinitos",rarity:"God"},
{name:"Los Bonecitos",rarity:"God"},
{name:"Los Crocodillitos",rarity:"God"},
{name:"Los Gatitos",rarity:"God"},
{name:"Los Liriliritos",rarity:"God"},
{name:"Los Tungtungtungcitos",rarity:"God"},
{name:"Macchiato Salsato",rarity:"God"},
{name:"Mastodontico Telepiedone",rarity:"God"},
{name:"Money Money Man",rarity:"God"},
{name:"Mummy Ambalabu",rarity:"God"},
{name:"Noo La Polizia",rarity:"God"},
{name:"Orcalero Orcala",rarity:"God"},
{name:"Orcalita Orcala",rarity:"God"},
{name:"Pandanini Frostini",rarity:"God"},
{name:"Perritino Donuttino",rarity:"God"},
{name:"Perritino Fiestanino",rarity:"God"},
{name:"Piccione Macchina",rarity:"God"},
{name:"Pop Pop Sahur",rarity:"God"},
{name:"Scimmia Parlante",rarity:"God"},
{name:"Skull Skull Skull",rarity:"God"},
{name:"Squalanana",rarity:"God"},
{name:"Statutino Libertino",rarity:"God"},
{name:"Tartaruga Cisterna",rarity:"God"},
{name:"Tentacolo Tecnico",rarity:"God"},
{name:"Tipi Topi Taco",rarity:"God"},
{name:"Toc Toc Toc Sahur",rarity:"God"},
{name:"Tootini Shrimpini",rarity:"God"},
{name:"Tractoro Dinosauro",rarity:"God"},
{name:"Tralalero Tralala",rarity:"God"},
{name:"Tralalita Tralala",rarity:"God"},
{name:"Trenostruzzo Turbo 3000",rarity:"God"},
{name:"Trigoligre Frutonni",rarity:"God"},
{name:"Trippi Troppi Troppa Trippa",rarity:"God"},
{name:"Tukanno Bananno",rarity:"God"},
{name:"Unclito Samito",rarity:"God"},
{name:"Urubini Flamenguini",rarity:"God"},
{name:"Yeti Claus",rarity:"God"},
// ⚫ Secret
{name:"1x1x1x1",rarity:"Secret"},
{name:"25",rarity:"Secret"},
{name:"67",rarity:"Secret"},
{name:"Agarrini La Palini",rarity:"Secret"},
{name:"Arcadopus",rarity:"Secret"},
{name:"Bacuru and Egguru",rarity:"Secret"},
{name:"Bisonte Giuppitere",rarity:"Secret"},
{name:"Blackhole Goat",rarity:"Secret"},
{name:"Boatito Auratito",rarity:"Secret"},
{name:"Bunnyman",rarity:"Secret"},
{name:"Burguro and Fryuro",rarity:"Secret"},
{name:"Burrito Bandito",rarity:"Secret"},
{name:"Capitano Moby",rarity:"Secret"},
{name:"Celestial Pegasus",rarity:"Secret"},
{name:"Cerberus",rarity:"Secret"},
{name:"Chachechi",rarity:"Secret"},
{name:"Chillin Chili",rarity:"Secret"},
{name:"Chipso and Queso",rarity:"Secret"},
{name:"Choco Rama",rarity:"Secret"},
{name:"Cigno Fulgoro",rarity:"Secret"},
{name:"Coffin Tung Tung Tung Sahur",rarity:"Secret"},
{name:"Cooki and Milki",rarity:"Secret"},
{name:"Cupid Cupid Sahur",rarity:"Secret"},
{name:"DJ Panda",rarity:"Secret"},
{name:"Donkeyturbo Express",rarity:"Secret"},
{name:"Dragon Cannelloni",rarity:"Secret"},
{name:"Dragon Gingerini",rarity:"Secret"},
{name:"Dul Dul Dul",rarity:"Secret"},
{name:"Eviledon",rarity:"Secret"},
{name:"Fishboard",rarity:"Secret"},
{name:"Fishino Clownino",rarity:"Secret"},
{name:"Griffin",rarity:"Secret"},
{name:"Guest 666",rarity:"Secret"},
{name:"Headless Horseman",rarity:"Secret"},
{name:"Hydra Dragon Cannelloni",rarity:"Secret"},
{name:"Jackorilla",rarity:"Secret"},
{name:"Jolly Jolly Sahur",rarity:"Secret"},
{name:"La Casa Boo",rarity:"Secret"},
{name:"La Cucaracha",rarity:"Secret"},
{name:"La Grande Combinasion",rarity:"Secret"},
{name:"Lavadorito Spinito",rarity:"Secret"},
{name:"Los Amigos",rarity:"Secret"},
{name:"Los Bros",rarity:"Secret"},
{name:"Los Burritos",rarity:"Secret"},
{name:"Los Cupids",rarity:"Secret"},
{name:"Los Planitos",rarity:"Secret"},
{name:"Los Puggies",rarity:"Secret"},
{name:"Los Quesadillas",rarity:"Secret"},
{name:"Los Sweethearts",rarity:"Secret"},
{name:"Lovin Rose",rarity:"Secret"},
{name:"Mariachi Corazoni",rarity:"Secret"},
{name:"Nuclearo Dinossauro",rarity:"Secret"},
{name:"Orcaledon",rarity:"Secret"},
{name:"Paradiso Axolottino",rarity:"Secret"},
{name:"Perrito Burrito",rarity:"Secret"},
{name:"Popcuru and Fizzuru",rarity:"Secret"},
{name:"Pot Pumpkin",rarity:"Secret"},
{name:"Pumpkini Spyderini",rarity:"Secret"},
{name:"Reinito Sleighito",rarity:"Secret"},
{name:"Santa Hotspot",rarity:"Secret"},
{name:"Serafinna Medusella",rarity:"Secret"},
{name:"Spaghetti Tualetti",rarity:"Secret"},
{name:"Spinny Hammy",rarity:"Secret"},
{name:"Swag Soda",rarity:"Secret"},
{name:"Telemorte",rarity:"Secret"},
{name:"Trickolino",rarity:"Secret"},
{name:"Vulturino Skeletono",rarity:"Secret"},
{name:"Zombie Tralala",rarity:"Secret"},
{name:"Secret Lucky Block",rarity:"Secret"},
// 👑 OG
{name:"John Pork",rarity:"OG"},
{name:"Meowl",rarity:"OG"},
{name:"Skibidi Toilet",rarity:"OG"},
{name:"Smurf Cat",rarity:"OG"},
{name:"Strawberry Elephant",rarity:"OG"},
];
